const gymleader1 = [
  {
    id: 542,
    name: 'leavanny',
    base: 235,
    extra: 0,
    weight: 205,
    height: 14,
    types: ['grass', 'bug'],
    moves: ['SWORDS-DANCE', 'RAZOR-LEAF', 'SUNNY-DAY', 'FACADE', 'BUG-BITE'],
  },
  {
    id: 267,
    name: 'beautifly',
    base: 185,
    extra: 0,
    weight: 284,
    height: 15,
    types: ['flying', 'bug'],
    moves: ['WHIRLWIND', 'SOLAR-BEAM', 'PSYCHIC', 'SLEEP-TALK'],
  },
  {
    id: 214,
    name: 'heracross',
    base: 190,
    extra: 0,
    weight: 544,
    height: 17,
    types: ['fighting', 'bug'],
    moves: ['HEADBUTT', 'FURY-ATTACK', 'RAIN-DANCE', 'ROCK-BLAST'],
  },
  {
    id: 168,
    name: 'ariados',
    base: 149,
    extra: 0,
    weight: 335,
    height: 11,
    types: ['poison', 'bug'],
    moves: ['POISON-STING', 'TOXIC', 'SECRET-POWER', 'ELECTROWEB'],
  },
  {
    id: 596,
    name: 'galvantula',
    base: 169,
    extra: 0,
    weight: 143,
    height: 8,
    types: ['electric', 'bug'],
    moves: ['THUNDERBOLT', 'TOXIC', 'LIGHT-SCREEN', 'FACADE'],
  },
  {
    id: 416,
    name: 'vespiquen',
    base: 200,
    extra: 0,
    weight: 385,
    height: 12,
    types: ['flying', 'bug'],
    moves: ['HYPER-BEAM', 'FURY-SWIPES', 'RAIN-DANCE', 'SUNNY-DAY'],
  },
];

const gymleader2 = [
  {
    id: 197,
    name: 'umbreon',
    base: 194,
    extra: 0,
    weight: 270,
    height: 11,
    types: ['dark'],
    moves: ['QUICK-ATTACK', 'NIGHTMARE', 'SHADOW-BALL', 'LAST-RESORT'],
  },
  {
    id: 430,
    name: 'honchkrow',
    base: 190,
    extra: 0,
    weight: 273,
    height: 9,
    types: ['flying', 'dark'],
    moves: ['WING-ATTACK', 'THIEF', 'AIR-CUTTER', 'FOUL-PLAY'],
  },
  {
    id: 461,
    name: 'weavile',
    base: 180,
    extra: 0,
    weight: 344,
    height: 13,
    types: ['ice', 'dark'],
    moves: ['ICE-PUNCH', 'QUICK-ATTACK', 'FURY-SWIPES', 'IRON-TAIL'],
  },
  {
    id: 675,
    name: 'pangoro',
    base: 180,
    extra: 0,
    weight: 1360,
    height: 21,
    types: ['dark', 'fighting'],
    moves: ['DOUBLE-TEAM', 'SUPERPOWER', 'DRAIN-PUNCH', 'KARATE-CHOP'],
  },
  {
    id: 634,
    name: 'zweilous',
    base: 160,
    extra: 0,
    weight: 510,
    height: 16,
    types: ['dragon','dark'],
    moves: ['BODY-SLAM', 'DRAGON-BREATH', 'DARK-PULSE', 'DRACO-METEOR'],
  },
  {
    id: 491,
    name: 'darkai',
    base: 277,
    extra: 0,
    weight: 510,
    height: 17,
    types: ['dark'],
    moves: ['NIGHT-SHADE', 'SLUDGE-BOMB', 'SHADOW-BALL', 'SHADOW-CLAW'],
  },
];

const gymleader3 = [
  {
    id: 303,
    name: 'mawile',
    base: 149,
    extra: 0,
    weight: 120,
    height: 10,
    types: ['fairy','steel'],
    moves: ['SEISMIC-TOSS', 'PAIN-SPLIT', 'METAL-BURST', 'MEGA-PUNCH'],
  },
  {
    id: 208,
    name: 'steelix',
    base: 189,
    extra: 0,
    weight: 4000,
    height: 97,
    types: ['ground', 'steel'],
    moves: ['BIND', 'DEFENSE-CURL', 'DRAGON-PULSE', 'STEALTH-ROCK'],
  },
  {
    id: 227,
    name: 'skarmory',
    base: 190,
    extra: 0,
    weight: 505,
    height: 19,
    types: ['flying', 'steel'],
    moves: ['SWORDS-DANCE', 'CUT', 'STEEL-WING', 'IRON-HEAD'],
  },
  {
    id: 437,
    name: 'bronzong',
    base: 188,
    extra: 0,
    weight: 1870,
    height: 20,
    types: ['psychic', 'steel'],
    moves: ['SOLAR-BEAM', 'ANCIENT-POWER', 'METAL-SOUND', 'TELEKINESIS'],
  },
  {
    id: 306,
    name: 'aggron',
    base: 250,
    extra: 0,
    weight: 3600,
    height: 25,
    types: ['rock','steel'],
    moves: ['SEISMIC-TOSS', 'FURY-CUTTER', 'ROCK-SMASH', 'GIGA-IMPACT'],
  },
  {
    id: 385,
    name: 'jirachi',
    base: 270,
    extra: 0,
    weight: 11,
    height: 3,
    types: ['psychic','steel'],
    moves: ['PSYSHOCK', 'IRON-HEAD', 'IRON-DEFENSE', 'FIRE-PUNCH'],
  },
];

export default {
  gymleader1,
  gymleader2,
  gymleader3
};
