const gymleader1 = [
  {
    id: 214,
    name: 'heracross',
    base: 185,
    extra: 0,
    weight: 540,
    height: 15,
    types: ['fighting', 'bug'],
    moves: [
      'SWORDS-DANCE',
      'CUT',
      'HEADBUTT',
      'HORN-ATTACK',
      'FURY-ATTACK',
      'TACKLE',
    ],
  },
  {
    id: 267,
    name: 'beautifly',
    base: 188,
    extra: 0,
    weight: 284,
    height: 10,
    types: ['flying', 'bug'],
    moves: [
      'GUST',
      'WHIRLWIND',
      'DOUBLE-EDGE',
      'HYPER-BEAM',
      'ABSORB',
      'MEGA-DRAIN',
      'SOLAR-BEAM',
    ],
  },
  {
    id: 49,
    name: 'venomoth',
    base: 168,
    extra: 0,
    weight: 125,
    height: 17,
    types: ['poison', 'bug'],
    moves: [
      'RAZOR-WIND',
      'GUST',
      'WHIRLWIND',
      'TACKLE',
      'TAKE-DOWN',
      'DOUBLE-EDGE',
      'SUPERSONIC',
    ],
  },
  {
    id: 469,
    name: 'yanmega',
    base: 190,
    extra: 0,
    weight: 515,
    height: 19,
    types: ['flying', 'bug'],
    moves: [
      'HEADBUTT',
      'TACKLE',
      'SUPERSONIC',
      'SONIC-BOOM',
      'HYPER-BEAM',
      'SOLAR-BEAM',
      'STRING-SHOT',
    ],
  },
  {
    id: 212,
    name: 'scizor',
    base: 185,
    extra: 0,
    weight: 1185,
    height: 18,
    types: ['steel', 'bug'],
    moves: [
      'RAZOR-WIND',
      'SWORDS-DANCE',
      'CUT',
      'HEADBUTT',
      'DOUBLE-EDGE',
      'LEER',
      'HYPER-BEAM',
    ],
  },
  {
    id: 542,
    name: 'Leavanny',
    base: 225,
    extra: 0,
    weight: 205,
    height: 12,
    types: ['grass', 'bug'],
    moves: [
      'SWORDS-DANCE',
      'CUT',
      'TACKLE',
      'HYPER-BEAM',
      'RAZOR-LEAF',
      'SOLAR-BEAM',
      'STRING-SHOT',
    ],
  },
];

const gymleader2 = [
  {
    id: 61,
    name: 'poliwhirl',
    base: 144,
    extra: 0,
    weight: 200,
    height: 12,
    types: ['water'],
    moves: [
      'DOUBLE-SLAP',
      'MEGA-PUNCH',
      'ICE-PUNCH',
      'MEGA-KICK',
      'HEADBUTT',
      'BODY-SLAM',
      'TAKE-DOWN',
    ],
  },
  {
    id: 131,
    name: 'lapras',
    base: 192,
    extra: 0,
    weight: 2200,
    height: 25,
    types: ['ice', 'water'],
    moves: ['WATER-GUN', 'HYDRO-PUMP', 'SURF', 'ICE-BEAM'],
  },
  {
    id: 73,
    name: 'tentacruel',
    base: 180,
    extra: 0,
    weight: 550,
    height: 16,
    types: ['poison', 'water'],
    moves: ['POISON-STING', 'MEGA-DRAIN', 'SKULL-BASH', 'FACADE'],
  },
  {
    id: 9,
    name: 'blastoise',
    base: 239,
    extra: 0,
    weight: 885,
    height: 16,
    types: ['water'],
    moves: ['ICE-BEAM', 'SEISMIC-TOSS', 'ICE-PUNCH', 'HYDRO-PUMP'],
  },
  {
    id: 230,
    name: 'kingdra',
    base: 247,
    extra: 0,
    weight: 1520,
    height: 18,
    types: ['dragon', 'water'],
    moves: ['BUBBLE-BEAM', 'WATERFALL', 'ICY-WIND', 'DRAGON-BREATH'],
  },
  {
    id: 503,
    name: 'samurott',
    base: 238,
    extra: 0,
    weight: 946,
    height: 15,
    types: ['water'],
    moves: ['HYDRO-PUMP', 'FOCUS-ENERGY', 'FURY-CUTTER', 'HYDRO-CANNON'],
  },
];

const gymleader3 = [
  {
    id: 587,
    name: 'emolga',
    base: 152,
    extra: 0,
    weight: 50,
    height: 5,
    types: ['flying','electric'],
    moves: ['GROWL', 'THUNDER', 'QUICK-ATTACK', 'SUPER-FANG'],
  },
  {
    id: 523,
    name: 'zebstrika',
    base: 184,
    extra: 0,
    weight: 795,
    height: 16,
    types: ['electric'],
    moves: ['TAIL-WHIP', 'THUNDERBOLT', 'LIGHT-SCREEN', 'RAIN-DANCE'],
  },
  {
    id: 181,
    name: 'ampharos',
    base: 233,
    extra: 0,
    weight: 620,
    height: 16,
    types: ['electric'],
    moves: ['THUNDER-PUNCH', 'THUNDERBOLT', 'FLASH', 'SHOCK-WAVE'],
  },
  {
    id: 26,
    name: 'raichu',
    base: 218,
    extra: 0,
    weight: 300,
    height: 8,
    types: ['electric'],
    moves: ['MEGA-PUNCH', 'THUNDER', 'IRON-TAIL', 'MAGNET-RISE'],
  },
  {
    id: 405,
    name: 'luxray',
    base: 245,
    extra: 0,
    weight: 430,
    height: 17,
    types: ['electric'],
    moves: ['BITE', 'THUNDER-WAVE', 'FURY-CUTTER', 'IRON-TAIL'],
  },
  {
    id: 466,
    name: 'electivire',
    base: 249,
    extra: 0,
    weight: 1388,
    height: 23,
    types: ['electric'],
    moves: ['THUNDER-PUNCH', 'FLAMETHROWER', 'EARTHQUAKE', 'RAIN-DANCE'],
  },
];

export default {
  gymleader1,
  gymleader2,
  gymleader3,
};
